version: '3.5'
services:

  frontend:
    build: './frontend'
    ports:
      - "3001:3000"
  
  books:
    build: './books'
    ports:
      - "3002:3000"
    volumes:
      - ./books/data/:/go/src/librarymanager/books/data/
    environment:
      REDIS_URL: redis:6379
      ACCESS_SECRET: SOMESECRET

  authorization:
    build: './authorization'
    ports:
      - "3004:3000"
    environment:
      ACCESS_SECRET: SOMESECRET
      
  reviews:
    build: './reviews'
    ports:
      - "3003:3000"
    volumes:
      - ./reviews/data/:/go/src/librarymanager/reviews/data/
    environment:
      REDIS_URL: redis:6379

  redis:
    image: redis:alpine
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - books
      - reviews
      - authorization
      - frontend