version: '3'
services:
  
  books:
    build: './books'
    ports:
      - "3002:3000"
  reviews:
    build: './reviews'
    ports:
      - "3003:3000"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - books
      - reviews